name: users_api_bloc
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  stacked_services: ^1.3.0
  get_it: ^7.6.0
  dio: ^5.3.2
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  formz: ^0.6.0
  flutter_dotenv: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
